version: "3.9"

services:

  api:
    build: .
    command: python main.py
    ports:
      - "5000:5000"

  worker:
    build: .
    command: python worker/redis_worker.py

  redis:
    image: redis:7

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password